### ISSUE TITLE
Unable to find webpack.config.js

### ISSUE THREAD

**Issue by cgatian** [xabikos/aspnet-webpack#13]
Im having some difficulty getting the webpack.config.js to read properly.

In Startup.cs::Configure() I have the following. 
`app.UseWebpack("webpack.config.js", "bundle.js", new WebpackDevServerOptions("localhost", 5000));`

And **webpack.config.js** sits in the app path.

![image](https://cloud.githubusercontent.com/assets/1752170/13691844/1d7432ea-e70a-11e5-822f-3acd433a6cdb.png)

```
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Webpack.Webpack.Execute(String configFile, String outputFileName, WebpackDevServerOptions devServerOptions)
   at Webpack.WebpackExtensions.UseWebpack(IApplicationBuilder app, String configFile, String outputFileName, WebpackDevServerOptions devServerOptions)
```

I've tried going up two directories "../../webpack.config.js" from #1 but no luck.  I verified I am running Kestrel.

I tried going back to version 1.1.0 as well.  Thank you for your time.

**Comment by cgatian** [comment]
Well I assumed it was my configuration file that wasn't found, but it was actually missing the **webpack-dev-server** dependency, and since I didn't have logger.  I see you are writing logs out that would've helped me had I had the logger configured in my pipeline.

You have some good logging information, I suggest mentioning enabling it to get better error messages. :smile:

**Comment by xabikos** [comment]
Hello cgatian. I have an open issue on analyzing the configuration and check that the required node modules are installed but it's not so easy to implement because of the various combination. But for sure I can check against webpack and webpack-dev-server that are absolute requirements. 

Regarding logging I didn't mention something as it's enabled by default so I assumed that most of the people will not remove it but probably I can add this in the documentation too.

Please let me know if you miss a feature on the project and if you have any ideas to further improve it.
