### ISSUE TITLE
Content-Length not set on outbound response

### ISSUE THREAD

**Issue by cgatian** [xabikos/aspnet-webpack#14]
When WebpackMiddleware.cs modifies the response stream content to inject a script tag the content length is not set to the new length of the response.  This causes the HTTP response to get cutoff prematurely.

![image](https://cloud.githubusercontent.com/assets/1752170/13726913/d421e442-e8a9-11e5-9d48-731f41844d4b.png)

Content length should be updated to **memStream.length** the when copying to the new stream.

**Comment by xabikos** [comment]
Thanks for the input @cgatian 

I tried to change the code and set the content length after [copying the stream](https://github.com/xabikos/aspnet-webpack/blob/master/src/Webpack/WebpackMiddleware.cs#L51) but I got an exception that `SetContentLength` method is not implemented in [FrameResponseStream](https://github.com/aspnet/KestrelHttpServer/blob/bc56d11d8ca9ba3e3b6a3c84900b0f8027ff2e96/src/Microsoft.AspNetCore.Server.Kestrel/Http/FrameResponseStream.cs#L60) class. 

Then I am not sure that this is the problem. Because I turned off the webpack middleware and in the response there is no Content-Length header too.

Could you provide an example that demonstrates the problem?

**Comment by cgatian** [comment]
All you need to do is set response.Headers.content length = stream.length

**Comment by xabikos** [comment]
How are you sure that this is the problem? I am just asking as I see that Kestel by default doesn't set this header. Maybe I am mistaken but if this was the problem then the server by default would have set this header for all html requests.

**Comment by cgatian** [comment]
That makes sense.
I cloned the repo and stepped though it. Setting the header ended up fixing it, but maybe there's something else I'm missing.

**Comment by xabikos** [comment]
Ok I will implement that change then and push a new version in nuget as soon as possible then. Thanks for catching that.

**Comment by xabikos** [comment]
I just pushed version [1.2.4](https://www.nuget.org/packages/Webpack/1.2.4) 
Please let me know if you have any other issues or ideas on improving the package
